---
- name: Install Docker and Docker Compose
  hosts: ec2_instances
  become: yes
  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present
        
    #- name: Install Docker Compose
    #  yum:
    #    name: docker-compose
    #    state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to Docker group
      command: usermod -aG docker ec2-user


